# --------------- APP Config ---------------
APP_NAME: "deep-activity-recognition"
APP_VERSION: 1.0.0

# --------------- PATH Config ---------------
PATH_DATA_ROOT: "data/volleyball"
PATH_TRACK_ANNOT_ROOT: "volleyball_tracking_annotation/volleyball_tracking_annotation"
PATH_VIDEOS_ROOT: "volleyball_/videos"
PATH_MODELS: "models"
PATH_MODELS_CHECKPOINTS: "checkpoints"
PATH_ASSETS: "assets"
PATH_METRICS: "metrics_plots"
# Hard write PATH_LOGS in [config_utils.py]
PATH_LOGS: "logs/baseline1/exp_1"
PATH_DATA_PROCESSING_MODULE: "data_processing"
PATH_UTILS_MODULE: "utils"

# --------------- General Config ---------------
NUM_ACTIVITY_LABELS: 8
NUM_ACTION_LABELS: 9
EPOCHS: 10
MODEL_MODE: train
TRAIN_IDS: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
VALIDATION_IDS: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
TEST_IDS: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

# --------------- B1 Config ---------------
# dataset
B1_FEATURES_SHAPE_0: 224
B1_FEATURES_SHAPE_1: 224
B1_LEFT_FRAMES: 5
B1_RIGHT_FRAMES: 4
# training
B1_TRAIN_EPOCHS: 10
B1_TRAIN_BATCH_SIZE: 32
B1_EVAL_BATCH_SIZE: 256
B1_LR: 0.0001
B1_FREEZE_BACKBONE: False
B1_NUM_WORKERS: 6
B1_OPTIMIZER: "AdamW"
B1_WEIGHT_DECAY: 0.001
B1_LOSS_FN: "cross_entropy_loss"
B1_EXPERIMENT_NUM: 1
