PATH_DATA_ROOT: "data/volleyball"
PATH_TRACK_ANNOT_ROOT: "volleyball_tracking_annotation/volleyball_tracking_annotation"
PATH_VIDEOS_ROOT: "volleyball_/videos"
PATH_MODELS: "models"
PATH_MODELS_CHECKPOINTS: "checkpoints"
PATH_ASSETS: "assets"
PATH_METRICS: "metrics_plots"
NUM_ACTIVITY_LABELS: 8
NUM_ACTION_LABELS: 9
EPOCHS: 10
MODEL_MODE: train

TRAIN_IDS: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
VALIDATION_IDS: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
